// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNi8ltDgwAHWewziiVz8WddZWotb5GvtQ',
    appId: '1:212658606737:web:415c4d8fe21c061e022530',
    messagingSenderId: '212658606737',
    projectId: 'gpoint-5c8d6',
    authDomain: 'gpoint-5c8d6.firebaseapp.com',
    storageBucket: 'gpoint-5c8d6.firebasestorage.app',
    measurementId: 'G-MTRKJM7WBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjdKJAzfkLh_NAhoxRNT18lQ3ywuQ7ohw',
    appId: '1:212658606737:android:6bc9bb0f673d4649022530',
    messagingSenderId: '212658606737',
    projectId: 'gpoint-5c8d6',
    storageBucket: 'gpoint-5c8d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAp6j2-cOHom5WHXo-mNB-2aZFzPeiwlc',
    appId: '1:212658606737:ios:0504a9d3218987f9022530',
    messagingSenderId: '212658606737',
    projectId: 'gpoint-5c8d6',
    storageBucket: 'gpoint-5c8d6.firebasestorage.app',
    iosClientId: '212658606737-fa7bp78tkbb16b7a5coaungpkej19fln.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAp6j2-cOHom5WHXo-mNB-2aZFzPeiwlc',
    appId: '1:212658606737:ios:0504a9d3218987f9022530',
    messagingSenderId: '212658606737',
    projectId: 'gpoint-5c8d6',
    storageBucket: 'gpoint-5c8d6.firebasestorage.app',
    iosClientId: '212658606737-fa7bp78tkbb16b7a5coaungpkej19fln.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNi8ltDgwAHWewziiVz8WddZWotb5GvtQ',
    appId: '1:212658606737:web:24421c436790a56f022530',
    messagingSenderId: '212658606737',
    projectId: 'gpoint-5c8d6',
    authDomain: 'gpoint-5c8d6.firebaseapp.com',
    storageBucket: 'gpoint-5c8d6.firebasestorage.app',
    measurementId: 'G-P9Z29M9NXX',
  );
}
